{% set python_min = "3.11" %}
{% set name = "codechembook" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/codechembook-{{ version }}.tar.gz
  sha256: b36c5ae4d90d521e5b25cc2463086c030e32d185da396f5c656ed321b819195b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - python-kaleido >=0.1.0
    - plotly
    - lmfit
    - numpy
    - scipy

test:
  imports:
    - codechembook
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/codechembook/
  summary: Companion package to 'Coding for Chemists' containing helpful functions for common tasks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ProfLear
